export const ALGOLIA_API_URL = "https://hn.algolia.com/api/v1/search_by_date";
export const ITEM_HEIGHT = 250; // height per article
export const INITIAL_NUM_TO_RENDER = 10;
export const WINDOW_SIZE = 10;
export const STALE_TIME = 1000 * 60 * 5; // 5 minutos
export const RETRY = 3;
export const REFETCH_INTERVAL = 1000 * 60 * 2; // Refetch every  2 min
export const searchTerms = [
  "AI",
  "machine learning",
  "blockchain",
  "crypto",
  "data science",
  "quantum",
  "cloud",
  "5G",
  "cybersecurity",
  "open-source",
  "startup",
  "tech",
  "software",
  "programming",
  "webdev",
  "apps",
  "artificial",
  "deep learning",
  "NLP",
  "IoT",
  "VR",
  "AR",
  "robotics",
  "automation",
  "big data",
  "privacy",
  "data protection",
  "ethics",
  "innovation",
  "gadget",
  "wearables",
  "news",
  "updates",
  "hardware",
  "computing",
  "languages",
  "devops",
  "tools",
  "community",
  "ecommerce",
  "fintech",
  "regulation",
  "digital",
  "UX",
  "UI",
  "design",
  "review",
  "cloud services",
  "IT",
  "analytics",
  "social media",
  "events",
  "conferences",
  "leaders",
  "founders",
  "VC",
  "investment",
  "disruptive",
  "policy",
  "giants",
  "development",
  "podcasts",
  "blogs",
  "coding",
  "OSS",
  "careers",
  "jobs",
  "best practices",
  "breaches",
  "scandals",
  "funding",
  "sustainable",
  "green",
  "innovations",
  "launches",
  "research",
  "models",
  "partnerships",
  "acquisitions",
  "patents",
  "appdev",
  "investments",
  "privacy",
  "digital rights",
  "debates",
  "tech",
  "AI",
  "machine",
  "block",
  "crypto",
  "data",
  "quantum",
  "cloud",
  "5G",
  "cyber",
  "open",
  "startup",
  "software",
  "web",
  "apps",
  "deep",
  "NLP",
  "IoT",
  "VR",
  "AR",
  "big",
  "privacy",
  "ethics",
  "gadget",
  "wear",
  "news",
  "update",
  "hardware",
  "language",
  "dev",
  "tools",
  "community",
  "ecom",
  "fin",
  "reg",
  "digital",
  "UX",
  "UI",
  "design",
  "review",
  "IT",
  "social",
  "event",
  "confer",
  "leader",
  "founder",
  "VC",
  "invest",
  "disrupt",
  "policy",
  "giant",
  "develop",
  "podcast",
  "blog",
  "code",
  "career",
  "job",
  "practice",
  "breach",
  "scandal",
  "fund",
  "sustain",
  "green",
  "launch",
  "research",
  "model",
  "partner",
  "acquire",
  "patent",
  "dev",
  "invest",
  "privacy",
  "rights",
  "debate",
  "AI",
  "machine learning",
  "blockchain",
  "cryptocurrency",
  "data science",
  "quantum computing",
  "cloud computing",
  "5G",
  "cybersecurity",
  "open-source",
  "startup",
  "tech industry",
  "software engineering",
  "programming",
  "web development",
  "mobile apps",
  "artificial intelligence",
  "deep learning",
  "natural language processing",
  "internet of things",
  "virtual reality",
  "augmented reality",
  "robotics",
  "automation",
  "big data",
  "privacy",
  "data protection",
  "ethics",
  "innovation",
  "technology trends",
  "gadget",
  "wearables",
  "tech news",
  "software updates",
  "hardware",
  "computing",
  "programming languages",
  "devops",
  "software tools",
  "developer community",
  "tech startup",
  "e-commerce",
  "fintech",
  "tech regulation",
  "digital transformation",
  "user experience",
  "user interface",
  "design thinking",
  "tech review",
  "cloud services",
  "IT security",
  "data analytics",
  "social media",
  "tech events",
  "tech conferences",
  "tech leaders",
  "startup founders",
  "venture capital",
  "investment",
  "disruptive technology",
  "tech policy",
  "tech giants",
  "software development",
  "tech podcasts",
  "tech blogs",
  "coding",
  "open-source software",
  "tech careers",
  "IT jobs",
  "software engineering best practices",
  "data breaches",
  "tech scandals",
  "tech startups funding",
  "technology ethics",
  "AI ethics",
  "sustainable tech",
  "green technology",
  "tech innovations",
  "tech product launches",
  "AI research",
  "ML models",
  "tech partnerships",
  "tech acquisitions",
  "software patents",
  "app development",
  "technology investments",
  "data privacy",
  "digital rights",
  "tech debates",
  "AI",
  "machine learning",
  "blockchain",
  "crypto",
  "data science",
  "quantum",
  "cloud",
  "5G",
  "cybersecurity",
  "open-source",
  "startup",
  "tech",
  "software",
  "programming",
  "webdev",
  "apps",
  "artificial",
  "deep learning",
  "NLP",
  "IoT",
  "VR",
  "AR",
  "robotics",
  "automation",
  "big data",
  "privacy",
  "data protection",
  "ethics",
  "innovation",
  "gadget",
  "wearables",
  "news",
  "updates",
  "hardware",
  "computing",
  "languages",
  "devops",
  "tools",
  "community",
  "ecommerce",
  "fintech",
  "regulation",
  "digital",
  "UX",
  "UI",
  "design",
  "review",
  "cloud services",
  "IT",
  "analytics",
  "social media",
  "events",
  "conferences",
  "leaders",
  "founders",
  "VC",
  "investment",
  "disruptive",
  "policy",
  "giants",
  "development",
  "podcasts",
  "blogs",
  "coding",
  "OSS",
  "careers",
  "jobs",
  "best practices",
  "breaches",
  "scandals",
  "funding",
  "sustainable",
  "green",
  "innovations",
  "launches",
  "research",
  "models",
  "partnerships",
  "acquisitions",
  "patents",
  "appdev",
  "investments",
  "privacy",
  "digital rights",
  "debates",
  "tech",
  "AI",
  "machine",
  "block",
  "crypto",
  "data",
  "quantum",
  "cloud",
  "5G",
  "cyber",
  "open",
  "startup",
  "software",
  "web",
  "apps",
  "deep",
  "NLP",
  "IoT",
  "VR",
  "AR",
  "big",
  "privacy",
  "ethics",
  "gadget",
  "wear",
  "news",
  "update",
  "hardware",
  "language",
  "dev",
  "tools",
  "community",
  "ecom",
  "fin",
  "reg",
  "digital",
  "UX",
  "UI",
  "design",
  "review",
  "IT",
  "social",
  "event",
  "confer",
  "leader",
  "founder",
  "VC",
  "invest",
  "disrupt",
  "policy",
  "giant",
  "develop",
  "podcast",
  "blog",
  "code",
  "career",
  "job",
  "practice",
  "breach",
  "scandal",
  "fund",
  "sustain",
  "green",
  "launch",
  "research",
  "model",
  "partner",
  "acquire",
  "patent",
  "dev",
  "invest",
  "privacy",
  "rights",
  "debate",
  "Linux Pipes Are Slow",
];
